version: '3.3'

services:

  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat-oss:6.6.0
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        com.docker.service.name: filebeat
        com.docker.stack.name: elk
      mode: replicated
      replicas: 3
    labels:
      com.docker.service.name: filebeat
      com.docker.stack.name: elk
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.ym
    networks:
      - elk

configs:
  filebeat_config:
    file: ./filebeat/config/filebeat.yml

networks:
  elk:
    driver: overlay
